name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK packages
        run: |
          sdkmanager "platforms;android-34" "platform-tools" "build-tools;34.0.0"

      - name: Create local.properties
        working-directory: project_ready_builder/project_ready_builder/project
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Install Gradle
        run: sudo apt-get install gradle -y

      - name: Build APK
        working-directory: project_ready_builder/project_ready_builder/project
        run: gradle assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: project_ready_builder/project_ready_builder/project/app/build/outputs/apk/debug/app-debug.apk
