name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3️⃣ Install Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: "34.0.0"
          components: platform-tools, build-tools;34.0.0, platforms;android-34

      # 4️⃣ Create local.properties
      - name: Create local.properties
        run: |
          SDK_PATH="${ANDROID_SDK_ROOT:-$HOME/Android/Sdk}"
          mkdir -p project_ready_builder/project_ready_builder/project
          echo "sdk.dir=${SDK_PATH}" > project_ready_builder/project_ready_builder/project/local.properties
        shell: bash

      # 5️⃣ Give permission to gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x project_ready_builder/project_ready_builder/project/gradlew

      # 6️⃣ Build APK
      - name: Build Debug APK
        working-directory: project_ready_builder/project_ready_builder/project
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      # 7️⃣ Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: project_ready_builder/project_ready_builder/project/app/build/outputs/apk/debug/app-debug.apk
