name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: project_ready_builder/project

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK 34
        run: |
          sdkmanager "platforms;android-34" "platform-tools" "build-tools;34.0.0"

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: project_ready_builder/project/app/build/outputs/apk/debug/app-debug.apk

      - name: Show direct download link
        run: |
          echo "### ✅ [Download APK](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
