name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Change to project directory
        run: cd project_ready_builder/project_ready_builder/project && pwd

      - name: Build APK
        working-directory: project_ready_builder/project_ready_builder/project
        run: |
          gradle build

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-apk
          path: project_ready_builder/project_ready_builder/project/app/build/outputs/apk//*.apk
